### PR TITLE
update CHANGES

### PR DESCRIPTION
**Pull request by palainp**

### CODE REVIEW

**Review by reynir — APPROVED** [review]
Thanks! Do you want me to merge this? Or are we waiting for something else?

**Comment by palainp** [comment]
Thank @reynir , I usually (well, based on the few couple of releases I've ever made :) ), wait for the opam-repository PR to be merged before concluding with the CHANGES PR.
Anyway, since that PR, @hannesm noticed that we need tcpip >= 8.2.0, maybe I can add it too to the changelog?

**Comment by reynir** [comment]
Yes, I guess it's always a good idea to add the constraints discovered by opam CI :-)

**Comment by hannesm** [comment]
I usually don't put these opam changes into the changelog -- the important part imho is to modify the opam file here in the repository (which I did by pushing to the main branch directly - https://github.com/mirage/mirage-qubes/commit/3634ec0d5cb16cdb358d39b3d3b0cb05773e349e)

**Pull request merged**
