### PR TITLE
Update for mirageos 3

### PR DESCRIPTION
**Pull request by yomimono**

### CODE REVIEW

**Comment by talex5** [comment]
Why is this for the `ipv4` branch? Is that our Mirage 3 branch?

**Comment by yomimono** [comment]
So far, functionally, yes, if I recall correctly?

**Comment by yomimono** [comment]
Let me be clearer: I would like to merge the `ipv4` branch into `master` in advance of the beta release process documented at https://github.com/mirage/mirageos-3-beta/issues/1 and the wider release into opam-repository.  Do you object and if so, to what and what would you prefer done differently?

**Comment by talex5** [comment]
OK, so the plan is that master won't build against the released version of mirage for a bit, until mirage 3 is released soon afterwards? Sounds OK to me.

I guess the other option is to add a constraint to master requiring Mirage 2, then release Mirage 3, then merge this. That would avoid any breakage. But the dev version of this library isn't exactly widely used...

**Comment by yomimono** [comment]
Currently in opam-repository, the constraint you mention exists:

```
~/opam-repository$ find packages/mirage-qubes -name opam|xargs grep mirage-type
packages/mirage-qubes/mirage-qubes.0.2/opam:  "mirage-types" {< "3.0.0"}
packages/mirage-qubes/mirage-qubes.0.3/opam:  "mirage-types" {< "3.0.0"}
packages/mirage-qubes/mirage-qubes.0.1/opam:  "mirage-types" {< "3.0.0"}
```

but you note correctly that it's not mirrored here.  #9 fixes that.

**Pull request merged**
